[package]
name = "blackipher"
version = "0.0.1"
edition = "2024"
rust-version = "1.85"

[dependencies]
sodiumoxide = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
iced = { version = "0.13", features = ["canvas", "tokio"] }
